// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQthtI6rNPC2Eq0VD0IBxQNiVz7Mwos8',
    appId: '1:20828963238:web:26278352b9454119b30f67',
    messagingSenderId: '20828963238',
    projectId: 'pocketplanner-6f870',
    authDomain: 'pocketplanner-6f870.firebaseapp.com',
    storageBucket: 'pocketplanner-6f870.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJcS_v8WMLuLCpaSIayDn8rNDytdgfSE',
    appId: '1:20828963238:android:e0943c142b02df21b30f67',
    messagingSenderId: '20828963238',
    projectId: 'pocketplanner-6f870',
    storageBucket: 'pocketplanner-6f870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-iHRkFVcxWZKu_VZJgWlQE4CFEsKTE1c',
    appId: '1:20828963238:ios:c170131292e206dbb30f67',
    messagingSenderId: '20828963238',
    projectId: 'pocketplanner-6f870',
    storageBucket: 'pocketplanner-6f870.firebasestorage.app',
    iosBundleId: 'com.example.pocketplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-iHRkFVcxWZKu_VZJgWlQE4CFEsKTE1c',
    appId: '1:20828963238:ios:c170131292e206dbb30f67',
    messagingSenderId: '20828963238',
    projectId: 'pocketplanner-6f870',
    storageBucket: 'pocketplanner-6f870.firebasestorage.app',
    iosBundleId: 'com.example.pocketplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARQthtI6rNPC2Eq0VD0IBxQNiVz7Mwos8',
    appId: '1:20828963238:web:1e256ac8887cbc65b30f67',
    messagingSenderId: '20828963238',
    projectId: 'pocketplanner-6f870',
    authDomain: 'pocketplanner-6f870.firebaseapp.com',
    storageBucket: 'pocketplanner-6f870.firebasestorage.app',
  );
}
